tamuhack-org/Ouroboros

ouroboros/templates/registration/login.html
Enabled the "password reset" link on the login page.
=> Added password reset feature.

ouroboros/customauth/forms.py, ouroboros/customauth/urls.py, ouroboros/customauth/views.py
=> Password reset form styling

ouroboros/hacker/admin.py
Administrators can now filter by in the sidebar of the admin dashboard.
=> Added custom filters to admin page

ouroboros/hacker/forms.py, ouroboros/hacker/tests/form_tests/application.py, ouroboros/hacker/tests/view_tests/application.py, ouroboros/hacker/views.py
=> Ensured that forms can't be altered after approval.

ouroboros/customauth/urls.py, ouroboros/ouroboros/settings/docker.py, ouroboros/templates/emails/activate_email.html, ouroboros/templates/registration/password_reset_email.html
=> Added some hacks to do HTTPS stuff.

ouroboros/api/permissions.py, ouroboros/api/tests/view_tests.py, ouroboros/api/views.py, ouroboros/hacker/models.py, ouroboros/hacker/tests/__init__.py, ouroboros/hacker/tests/model_tests/__init__.py, ouroboros/hacker/tests/model_tests/rsvp.py, ouroboros/ouroboros/settings/base.py, ouroboros/shared/test.py, requirements.txt
=> Enabled QR code generation, attaching to emails.

ouroboros/hacker/models.py
=> Added ENGR as a major.

ouroboros/hacker/models.py, ouroboros/hacker/tests/form_tests/application.py, ouroboros/shared/test.py
=> Added filetype validators

ouroboros/static/style.css, ouroboros/templates/hacker/status.html, ouroboros/templates/registration/check_email.html
Fixes other responsive issues
Closes #111
=> Closes #85

ouroboros/static/style.css
=> Fix error styling

hiss/application/admin.py
=> Added datetime_submitted to list_display.

hiss/application/admin.py, hiss/application/tests/admin_tests/application.py, hiss/rsvp/models.py, hiss/rsvp/tests/__init__.py, hiss/rsvp/tests/model_tests/__init__.py, hiss/rsvp/tests/model_tests/rsvp.py, hiss/templates/application/emails/approved.html, hiss/templates/application/emails/rejected.html, hiss/templates/rsvp/emails/created.html, hiss/templates/rsvp/emails/updated.html
Made use of Django's `send_mass_mail` functionality to improve mass-email dispatch times, and customization tests to ensure that emails are being customized correctly.
Closes #176 
Closes #177
=> Mass email and customization functionality

.idea/vcs.xml, hiss/application/views.py, hiss/hiss/settings/base.py, hiss/hiss/settings/customization.py, hiss/rsvp/views.py, hiss/static/check_inbox.css, hiss/templates/application/application_form.html, hiss/templates/base.html, hiss/templates/registration/check_inbox.html, hiss/templates/registration/emails/password_reset.html, hiss/templates/registration/login.html, hiss/templates/registration/password_reset_complete.html, hiss/templates/registration/password_reset_confirm.html, hiss/templates/registration/password_reset_done.html, hiss/templates/registration/password_reset_form.html, hiss/templates/registration/resend_activation.html, hiss/templates/registration/signup.html, hiss/templates/rsvp/rsvp_form.html, hiss/templates/status/status.html
=> Included styling.

hiss/application/views.py
=> Edit redirect

hiss/application/models.py
=> Added summer semester to graduation dates.

hiss/application/views.py, hiss/rsvp/tests/view_tests/create.py, hiss/rsvp/tests/view_tests/update.py, hiss/rsvp/views.py, hiss/templates/rsvp/rsvp_decline.html, hiss/templates/rsvp/rsvp_form.html, hiss/templates/status/status.html
=> Added fixes for RSVP if declined.

hiss/static/style.css, hiss/templates/registration/login.html, hiss/templates/status/status.html
I'll be there and I can't make it buttons are inline
=> I'll be there and I can't make it buttons are inline

hiss/static/main.js, hiss/templates/base.html
=> Added jQuery for prefer to self-describe

hiss/hiss/settings/base.py
=> Increased overall upload size.

hiss/static/style.css, hiss/templates/status/status.html
=> Fixing alignment/margins

hiss/application/forms.py, hiss/application/models.py, hiss/application/tests/form_tests/application_form.py
Closes #295 . There was a `KeyError` happening because of incomplete testing.
=> Rewrote "other" field validation in a semantic-Django way.

hiss/hiss/settings/base.py, hiss/hiss/urls.py, hiss/user/models.py, hiss/user/tests/model_tests/__init__.py, hiss/user/tests/model_tests/receivers.py, hiss/volunteer/models.py, hiss/volunteer/permissions.py, hiss/volunteer/serializers.py, hiss/volunteer/tests/__init__.py, hiss/volunteer/tests/test_case.py, hiss/volunteer/tests/views/__init__.py, hiss/volunteer/tests/views/create_food_event.py, hiss/volunteer/tests/views/create_workshop_event.py, hiss/volunteer/tests/views/search.py, hiss/volunteer/tests/views/user_checkin.py, hiss/volunteer/tests/views/user_summary.py, hiss/volunteer/tests/views/volunteer_login.py, hiss/volunteer/urls.py, hiss/volunteer/views.py
=> Volunteer endpoints

hiss/templates/registration/password_reset_form.html
=> Fixed Typo

README.md
I left my name and a fixed URL in the README
Sorry about that :/
=> Replace exact image path with relative

Dockerfile, Dockerfile.dev, hiss/hiss/settings/base.py, hiss/hiss/settings/deployment.py, hiss/requirements.txt
Copied configuration that works for TD in prod on Heroku.
=> Make static files work in production.

hiss/hiss/settings/deployment.py, hiss/static/howdyhack_official_logo.svg, hiss/static/style.css
=> Updated styling and mailgun domain.

hiss/templates/application/emails/confirmed-old.html, hiss/templates/application/emails/confirmed.html
=> Update confirmation email template

hiss/application/admin.py, hiss/application/models.py
Added function in models.py to update meal group column after confirmation based on the last assigned meal group
=> Add meal groups

hiss/templates/dashboard_base.html
Fixed the logout button on status page by changing out the anchor tag to a button with form that uses POST request. Used inline styling to maintain the same design as before.
=> Fix logout button by switching from GET to POST method

hiss/application/constants.py
Removed XS and XXS from possible shirt sizes.
=> remove XS and XXS from shirt sizes
